### ISSUE TITLE
Multiple SLMdisplay instances

### ISSUE THREAD

**Issue by wkrasnicki** [wavefrontshaping/slmPy#6]
Hi, I'm trying to use two SLMs in an experiment, but once the second SLMdisplay object gets instantiated, they stop responding to image changes. I have tried changing EVT_NEW_IMAGE to an instance variable, but to no avail and I am of the opinion that wx may be to blame, as it does not support multiple wx.app instances.

Perhaps you had some luck running two SLMs from a single program? Any help would be greatly appreciated.

**Comment by fschiffers** [comment]
could you provide more information how this was done ?

**Comment by wkrasnicki** [comment]
I don't work on that project anymore and don't have access to the code, but from what I recall we wrapped each SLM in a worker run using Python's `multiprocessing` library. The images to be displayed were sent using a pipe, but something was wrong with that solution and we changed the lib from `multiprocessing` to `pyqtgraph.multiprocess`
